-- ============================================================
--  TopNotes — PRODUCTION (Render PostgreSQL) FULL schema sync
--
--  One consolidated, idempotent script that applies every schema change the
--  current backend needs. It combines:
--    • PROD_DB_MIGRATION_AUTH.sql          (email verification + optional phone)
--    • PROD_DB_MIGRATION_CONSENT.sql       (agreement_documents, consent_records)
--    • PROD_DB_MIGRATION_NOTE_APPROVAL.sql (notes.status new states)
--    • PROD_DB_MIGRATION_NOTE_PUBLISH_GATE.sql (notes.approved + rejection_reason)
--
--  WHY THIS IS NEEDED (and ddl-auto=update isn't enough):
--    Hibernate's `ddl-auto=update` cannot add a NOT NULL column WITHOUT a default
--    to a table that already has rows — so `users.email_verified` and
--    `notes.approved` silently fail to be created, then every query that selects
--    them throws e.g. `ERROR: column n1_0.approved does not exist`. These ALTERs
--    add the columns WITH a default, which works on populated tables.
--
--  RUN ONCE (safe to re-run — every statement is IF NOT EXISTS / DROP IF EXISTS):
--    psql "postgresql://USER:PASS@HOST/DB?sslmode=require" -f docs/PROD_DB_MIGRATION_ALL.sql
--  (or paste into the Render DB console / pgAdmin connected to the prod DB)
--
--  AFTER RUNNING: restart the backend so AgreementSeeder seeds the Seller
--  Agreement + Originality Declaration and the app picks up the clean schema.
-- ============================================================

BEGIN;

-- ── 1. Auth: email verification + optional phone ────────────
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;
-- Grandfather existing accounts as verified so the seller-test gate / buyer nudge
-- don't disrupt current users. New signups insert FALSE.
UPDATE users SET email_verified = TRUE WHERE email_verified = FALSE;
ALTER TABLE users ALTER COLUMN phone DROP NOT NULL;

CREATE TABLE IF NOT EXISTS email_verification_tokens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_hash   VARCHAR(255) NOT NULL,
  expires_at  TIMESTAMP(6) NOT NULL,
  consumed_at TIMESTAMP(6),
  attempts    INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMP(6) NOT NULL,
  user_id     BIGINT NOT NULL REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_evt_user ON email_verification_tokens(user_id);

-- ── 2. Consent infrastructure ───────────────────────────────
CREATE TABLE IF NOT EXISTS agreement_documents (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type         VARCHAR(40)  NOT NULL,
  version      INTEGER      NOT NULL,
  title        VARCHAR(200) NOT NULL,
  body         TEXT         NOT NULL,
  content_hash VARCHAR(64)  NOT NULL,
  active       BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMP(6) NOT NULL,
  CONSTRAINT uk_agreement_type_version UNIQUE (type, version)
);
CREATE TABLE IF NOT EXISTS consent_records (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT      NOT NULL REFERENCES users(id),
  agreement_type VARCHAR(40) NOT NULL,
  version        INTEGER     NOT NULL,
  content_hash   VARCHAR(64) NOT NULL,
  note_id        BIGINT,
  ip_address     VARCHAR(45),
  user_agent     VARCHAR(512),
  accepted_at    TIMESTAMP(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_consent_user_type ON consent_records(user_id, agreement_type);
CREATE INDEX IF NOT EXISTS idx_consent_note ON consent_records(note_id);

-- ── 3. Note status: allow the new publication states ────────
ALTER TABLE notes DROP CONSTRAINT IF EXISTS notes_status_check;
ALTER TABLE notes ADD CONSTRAINT notes_status_check
  CHECK (status IN ('PENDING_REVIEW', 'REJECTED', 'ACTIVE', 'INACTIVE', 'DELETED'));

-- ── 4. Publish gate + rejection reason ──────────────────────
--  (fixes "ERROR: column n1_0.approved does not exist")
ALTER TABLE notes ADD COLUMN IF NOT EXISTS approved BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE notes ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(1000);
-- Existing live notes were admin-approved — keep them publishable.
-- Review any ACTIVE note you suspect bypassed review BEFORE running this.
UPDATE notes SET approved = TRUE WHERE status = 'ACTIVE';

COMMIT;

-- ── Optional: promote a signed-up user to ADMIN ─────────────
-- Sign up normally first (so the password is hashed by the app), then run:
--   UPDATE users SET role = 'ADMIN', email_verified = TRUE, status = 'ACTIVE'
--   WHERE email = 'topnotes2026@gmail.com';
-- Log out and back in afterwards so the new role is in a fresh JWT.
